### PR TITLE
Use a specific release branch instead of the master branch

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

### CODE REVIEW

**Comment by dvdplm** [comment]
I think that `master` should use the latest master branch, but when we cut `substrate-archive` releases we should build with a specific (released) version of polkadot. I am aware of the quick development pace on `polkadot` can make this painful, but still think it's best to make development on `archive` stay as close as possible to the upstream cutting edge. Am I wrong?

@insipx wdyt?

**Comment by insipx** [comment]
Yeah, I think we tried attaching master to specific releases of polkadot in the past, and it caused more headache than it was worth (updating/compile errors/etc). However those issues were caused because the version of substrate pointed at by polkadot dependencies was `master` but I see that has changed now. 

I think for ease & speed of development archive should still point at substrate master. This comes in particular use when we are developing joint features (state-tracing comes to mind) that are being merged into substrate. Currently we would not have to wait for a polkadot release to push to master to get those new substrate features.


i think for substrate releases freezing polkadot versions is what we should switch to doing. We would have to make a release coinciding with each polkadot release, but that would make the compiles/releases generally more consistent/stable

**Comment by dvdplm** [comment]
> i think for substrate releases freezing polkadot versions is what we should switch to doing. We would have to make a release coinciding with each polkadot release, but that would make the compiles/releases generally more consistent/stable

Do you think we can release a `0.5.1` that is pinned to a polkadot release?

**Comment by dvdplm** [comment]
Closing in favour of #267 – thank you @koushiro for the suggestion and the code changes.

**Pull request closed without merging**
